/**
 * GoldenFloat — Binary GF ladder C++ wrappers (header-only, thin FFI over the C-ABI).
 *
 * The φ²-sized binary rungs (mirroring Gf16), each with the full op set:
 *   Gf8  [1:3:4]  b3    ~[0.25, 15.5]     (uint8_t carrier)
 *   Gf12 [1:4:7]  b7    ~[0.016, 256]     (uint16_t carrier)
 *   Gf20 [1:7:12] b63   wide              (uint32_t carrier)
 *   Gf24 [1:9:14] b255  very wide         (uint32_t carrier)
 *   Gf32 [1:12:19] b2047 very wide        (uint32_t carrier)
 *
 * Gf16 [1:6:9] b31 is the rich API (gf16.hpp). Gf4 is omitted — a 1-bit exponent
 * leaves no normal values.
 *
 *   #include <goldenfloat/gf_ladder.hpp>
 *   auto a = goldenfloat::Gf12::from_f32(3.14159f);
 *   float p = (a * a).to_f32();
 *
 * phi^2 + 1/phi^2 = 3 | TRINITY
 * MIT License — Copyright (c) 2026 Trinity Project
 */

#ifndef GOLDENFLOAT_GF_LADDER_HPP
#define GOLDENFLOAT_GF_LADDER_HPP

#include <cstdint>
#include <ostream>

#include "gf_ladder.h"

namespace goldenfloat {

// One class per rung, generated by a macro over (Name, carrier type, prefix, payload mask).
#define GOLDENFLOAT_GF_CLASS(Name, T, PFX, MASK)                                     \
    class Name {                                                                     \
    public:                                                                          \
        using value_type = T;                                                        \
        Name() : _value(0) {}                                                        \
        explicit Name(value_type raw) : _value(raw & (MASK)) {}                      \
        static Name from_f32(float x) { return Name(PFX##_from_f32(x)); }            \
        float to_f32() const { return PFX##_to_f32(_value); }                        \
        Name operator+(const Name& o) const { return Name(PFX##_add(_value, o._value)); } \
        Name operator-(const Name& o) const { return Name(PFX##_sub(_value, o._value)); } \
        Name operator*(const Name& o) const { return Name(PFX##_mul(_value, o._value)); } \
        Name operator/(const Name& o) const { return Name(PFX##_div(_value, o._value)); } \
        Name operator-() const { return Name(PFX##_neg(_value)); }                   \
        Name abs() const { return Name(PFX##_abs(_value)); }                         \
        bool is_finite() const { return PFX##_is_finite(_value) != 0; }              \
        value_type raw() const { return _value; }                                    \
        friend std::ostream& operator<<(std::ostream& os, const Name& g) {           \
            os << #Name "(" << g.to_f32() << ")";                                     \
            return os;                                                               \
        }                                                                            \
    private:                                                                         \
        value_type _value;                                                           \
    };

GOLDENFLOAT_GF_CLASS(Gf8, uint8_t, gf8, 0xFFu)
GOLDENFLOAT_GF_CLASS(Gf12, uint16_t, gf12, 0xFFFu)
GOLDENFLOAT_GF_CLASS(Gf20, uint32_t, gf20, 0xFFFFFu)
GOLDENFLOAT_GF_CLASS(Gf24, uint32_t, gf24, 0xFFFFFFu)
GOLDENFLOAT_GF_CLASS(Gf32, uint32_t, gf32, 0xFFFFFFFFu)

#undef GOLDENFLOAT_GF_CLASS

} // namespace goldenfloat

#endif // GOLDENFLOAT_GF_LADDER_HPP
